language: python

python:
  - 2.7
  - 3.4
  - 3.5

services:
  - mysql

env:
  global:
    - PW_TEST_DB_USER=travis
    - PW_TEST_DB_PASS=""
    - PW_SKIP_BROWSER_TESTS=yes

before_script:
  - mysql -e 'create database patchwork character set utf8;'

install:
  - pip install tox-travis

script:
  - tox
